//
//  PlaceTypes.swift
//  GoogleMapsApp
//
//  Created by Vinicius Carvalho on 24/03/20.
//  Copyright © 2020 Vinicius Carvalho. All rights reserved.
//

import Foundation

enum PlaceTypes: String {
    case accounting = "accounting"
    case airport = "airport"
    case amusement_park = "amusement_park"
    case aquarium = "aquarium"
    case art_gallery = "art_gallery"
    case atm = "atm"
    case bakery = "bakery"
    case bank = "bank"
    case bar = "bar"
    case beauty_salon = "beauty_salon"
    case bicycle_store = "bicycle_store"
    case book_store = "book_store"
    case bowling_alley = "bowling_alley"
    case bus_station = "bus_station"
    case cafe = "cafe"
    case campground = "campground"
    case car_dealer = "car_dealer"
    case car_rental = "car_rental"
    case car_repair = "car_repair"
    case car_wash = "car_wash"
    case casino = "casino"
    case cemetery = "cemetery"
    case church = "church"
    case city_hall = "city_hall"
    case clothing_store = "clothing_store"
    case convenience_store = "convenience_store"
    case courthouse = "courthouse"
    case dentist = "dentist"
    case department_store = "department_store"
    case doctor = "doctor"
    case drugstore = "drugstore"
    case electrician = "electrician"
    case electronics_store = "electronics_store"
    case embassy = "embassy"
    case fire_station = "fire_station"
    case florist = "florist"
    case funeral_home = "funeral_home"
    case furniture_store = "furniture_store"
    case gas_station = "gas_station"
    case grocery_or_supermarket = "grocery_or_supermarket"
    case gym = "gym"
    case hair_care = "hair_care"
    case hardware_store = "hardware_store"
    case hindu_temple = "hindu_temple"
    case home_goods_store = "home_goods_store"
    case hospital = "hospital"
    case insurance_agency = "insurance_agency"
    case jewelry_store = "jewelry_store"
    case laundry = "laundry"
    case lawyer = "lawyer"
    case library = "library"
    case light_rail_station = "light_rail_station"
    case liquor_store = "liquor_store"
    case local_government_office = "local_government_office"
    case locksmith = "locksmith"
    case lodging = "lodging"
    case meal_delivery = "meal_delivery"
    case meal_takeaway = "meal_takeaway"
    case mosque = "mosque"
    case movie_rental = "movie_rental"
    case movie_theater = "movie_theater"
    case moving_company = "moving_company"
    case museum = "museum"
    case night_club = "night_club"
    case painter = "painter"
    case park = "park"
    case parking = "parking"
    case pet_store = "pet_store"
    case pharmacy = "pharmacy"
    case physiotherapist = "physiotherapist"
    case plumber = "plumber"
    case police = "police"
    case post_office = "post_office"
    case primary_school = "primary_school"
    case real_estate_agency = "real_estate_agency"
    case restaurant = "restaurant"
    case roofing_contractor = "roofing_contractor"
    case rv_park = "rv_park"
    case school = "school"
    case secondary_school = "secondary_school"
    case shoe_store = "shoe_store"
    case shopping_mall = "shopping_mall"
    case spa = "spa"
    case stadium = "stadium"
    case storage = "storage"
    case store = "store"
    case subway_station = "subway_station"
    case supermarket = "supermarket"
    case synagogue = "synagogue"
    case taxi_stand = "taxi_stand"
    case tourist_attraction = "tourist_attraction"
    case train_station = "train_station"
    case transit_station = "transit_station"
    case travel_agency = "travel_agency"
    case university = "university"
    case veterinary_care = "veterinary_care"
    case zoo = "zoo"
}
